  version: 2.1
  orbs:
    kubernetes: circleci/kubernetes@0.11.0
  jobs:
    create-update:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - kube-orb/install-kubectl
        - kube-orb/create-or-update-resource:
            get-rollout-status: true
            resource-file-path: tests/nginx-deployment/deployment.yaml
            resource-name: deployment/nginx-deployment
            show-kubectl-command: true
  orbs:
    kube-orb: circleci/kubernetes@0.11.0
  version: 2.1

